[build]
publish = "output"
command = """
  mkdir notebook; curl -L https://github.com/valpackett/Notebook/archive/94bd85d9e29ab4c478b197d406d83ab89271f2ef.tar.gz | tar -xvzf - -C notebook --strip-components=1 &&
  TIDDLYWIKI_THEME_PATH=notebook/themes TIDDLYWIKI_PLUGIN_PATH=notebook/plugins npx tiddlywiki@5.3.0 --build
"""

[[headers]]
for = "/*"
[headers.values]
x-content-type-options = "nosniff"
x-frame-options = "SAMEORIGIN"
referrer-policy = "no-referrer-when-downgrade"

[[redirects]]
from = "/w/:name/:file"
to = "/app/:file"
status = 200
